version: '3.1'

networks:
  external-network:
    external:
      name: external-network

services:

  sbt:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sbt
    ports:
      - "8080:8080"
    volumes:
      - "./:/root/project"
    networks:
      - external-network
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doobie
      POSTGRES_DB: doobie
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always
    container_name: postgres
    networks:
      - external-network